name: instagram_clone
description: An Instagram clone built using flutter and firebase

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+4
  image_picker: ^0.6.1+8
  cached_network_image: ^1.1.2+1
  firebase_storage: ^3.0.6
  flutter_image_compress: ^0.6.3
  path_provider: ^1.4.0
  uuid: ^2.0.2
  provider: ^3.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf